<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toolbox.Application\Toolbox.Application.csproj" />
    <ProjectReference Include="..\Toolbox.Infrastructure\Toolbox.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
